# Container for mysql
# cmd: docker compose up -d

services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    environment:
      # MYSQL_DATABASE: orders_db  # Creates the database
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3316:3306"
# 3306 occupied already
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - microservices-ecommerce
    restart: always

  # avoid permission issues
  #volumes:
  #mysql:

  # Define the network
networks:
  microservices-ecommerce:
    driver: bridge